---
title: "captnd_dashboard_glossary"
author: "Luke Taylor"
date: "2025-11-21"
output: html_document
---

```{r setup, include = FALSE}

# Psychological Therapies

knitr::opts_chunk$set(echo = FALSE, dpi = 300)
library(ggplot2)
library(scales)
library(flextable)
library(officer)
library(magrittr)
library(arrow)
library(tidyverse)

# define dataset selector variable
dataset_choice <- "PT"
month_end <- "2025-09-01"
dataset_type_o <- "dataset_type"
hb_name_o <- "hb_name"


# source data for tables and inline values
source("/PHI_conf/MentalHealth5/CAPTND/CAPTND_shorewise/scripts/luke/CAPTND/07_publication/script/functions/source_data_for_markdown.R", local = knitr::knit_global())
```

 
**CAMHS**  
Child and Adolescent Mental Health Services provided by NHS Scotland. Services
are provided by teams of clinicians including psychiatrists, mental health nurses,
clinical psychologists, occupational therapists and other allied health professionals.
These services are based mainly in outpatient clinics and in the community. CAMHS
are multi-disciplinary teams that provide treatment and/or interventions for children
and young people experiencing mental health problems. Where a child or young person
is awaiting an assessment for a neurodevelopmental condition such as ASD, or ADHD,
they may not be appropriate for CAMHS. This is because they do not meet the National Referral
Criteria as described in the CAMHS national service specification and may instead
be referred onto a neurodevelopmental (ND) pathway. This release does not report
on the neurodevelopmental (ND) pathway including those children and young people
on the neurodevelopmental waiting list.

**Children and young people**  
The people served by CAMHS. Some areas provide services for all those under 18, 
while others offer services to those over 16 only if they are in full time education.

**Psychological Therapies**  
Psychological Therapies refer to a range of interventions, based on psychological
concepts and theory, which are designed to help people understand and make changes
to their thinking, behaviour, and relationships in order to relieve distress and
to improve functioning. The standard applies specifically to psychological therapies
for treatment of a mental illness or disorder.

**Key variables**  
The combination of identifying variables - including 'UCPN' and 'CHI'/'UPI' -
allowing a patient pathway to be created, which enables further analysis in CAPTND.

**Mean**  
The arithmetical average value i.e. total of a number of values / the total number of 
values.

**Median**  
The middle value when the data values in a dataset are ranked in increasing (or 
decreasing) order of magnitude.

**Total appointments**  
The total number of appointments recorded in CAPTND, whether attended or not. An 
individual can have more than one appointment on a given day.

**First contact appointment**  
The first appointment date that appears in an individual's care pathway.

**DNA Rate**  
Did not attend (DNA) refers to appointments in which a patient did not attend and
gave no prior warning. The DNA rate is the proportion of appointments for which
this occurs out of all appointments in a given period. If for first contact appointments only this
is referred to as the *first contact DNA rate*.

**Region**  
The health boards that make up NHSScotland can be divided into three geographical
regions:  
East region: *Borders, Fife, Lothian*  
North region: *Highland, Grampian, Orkney, Tayside, Western Isles, Shetland*  
West region: *Ayrshire & Arran, Greater Glasgow & Clyde, Lanarkshire, Forth Valley, Dumfries & Galloway*  

**Official statistics/Official statistics in development:**  
[Official statistics](https://code.statisticsauthority.gov.uk/glossary/#pid-official-statistics)
are statistics produced on behalf of the UK government, while [official statistics in development](https://code.statisticsauthority.gov.uk/glossary/#pid-official-statistics-in-development)
are official statistics which are undergoing a development, and are under testing
by users for quality, trustworthiness, and value.
